import { StyleSheet, Dimensions } from 'react-native';

const { width: SCREEN_WIDTH } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#ffffff', paddingTop: 24 },
  content: { paddingHorizontal: 16, paddingTop: 48, paddingBottom: 120 },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 8,
    marginBottom: 16,
  },
  header: { fontSize: 32, fontWeight: '700' },
  templateButton: {
    fontSize: 16,
    fontWeight: '500',
    color: '#007AFF',
  },
  loadingText: {
    textAlign: 'center',
    color: '#999',
    marginTop: 48,
  },
  yesterdayIndicator: {
    alignItems: 'center',
    justifyContent: 'center',
    height: 32,
    marginBottom: 8,
  },
  yesterdayText: {
    fontSize: 13,
    color: '#aaa',
    fontStyle: 'italic',
  },
  workoutDayHeader: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: '#f9f9f9',
    borderRadius: 8,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    position: 'relative',
  },
  workoutDayHeaderText: {
    fontSize: 18,
    fontWeight: '600',
  },
  daySelectorContainer: {
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: '#e5e5e5',
    paddingVertical: 16,
    marginBottom: 16,
  },
  daySelectorTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333',
    textAlign: 'center',
    marginBottom: 16,
  },
  dayButton: {
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 20,
    marginRight: 8,
    backgroundColor: '#f8f8f8',
  },
  dayButtonText: {
    fontWeight: '600',
    color: '#000000',
  },
  restDayButton: {
    backgroundColor: '#f0f0f0',
    borderStyle: 'dashed',
    borderWidth: 1,
    borderColor: '#ccc',
  },
  restDayButtonText: {
    color: '#999',
    fontStyle: 'italic',
  },
  restDayBadge: {
    fontSize: 10,
    fontWeight: 'bold',
    color: '#999',
    position: 'absolute',
    top: -5,
    right: -5,
    backgroundColor: '#f0f0f0',
    paddingHorizontal: 4,
    borderRadius: 4,
  },
  timerToggle: {
    position: 'absolute',
    left: 8,
    top: 0,
    bottom: 0,
    justifyContent: 'center',
    paddingHorizontal: 8,
  },
  timerToggleText: {
    color: '#007AFF',
    fontSize: 12,
    fontWeight: '500',
  },
  restToggle: {
    position: 'absolute',
    right: 8,
    top: 0,
    bottom: 0,
    justifyContent: 'center',
    paddingHorizontal: 8,
  },
  restToggleText: {
    color: '#007AFF',
    fontSize: 12,
    fontWeight: '500',
  },
  exerciseRowContainer: {
    backgroundColor: '#DC2626',
  },
  exerciseDeleteActionContainer: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'center',
    alignItems: 'flex-end',
  },
  exerciseDeleteButton: {
    justifyContent: 'center',
    alignItems: 'center',
    width: 100,
    height: '100%',
    paddingRight: 20,
  },
  addDayButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#e5e5e5',
    borderStyle: 'dashed',
  },
  addDayButtonText: {
    marginLeft: 4,
    color: '#999',
    fontWeight: '500',
  },
  row: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#e5e5e5',
    backgroundColor: 'white',
    minHeight: 48,
  },
  tableHeader: {
    backgroundColor: '#f8f8f8',
    borderTopWidth: 1,
    borderTopColor: '#e5e5e5',
  },
  headerText: { padding: 12, fontWeight: '600', fontSize: 12, color: '#999', textTransform: 'uppercase', letterSpacing: 0.5 },
  exerciseCol: { flex: 12 },
  numberCol: { flex: 1, textAlign: 'center', minWidth: 70 },
  cell: { padding: 12, fontSize: 16, alignSelf: 'center', minHeight: 48 },
  addButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 16,
  },
  addButtonText: { fontSize: 16, fontWeight: '500' },
  emptyStateContainer: {
    padding: 32,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 24,
  },
  emptyStateText: {
    fontSize: 16,
    color: '#999',
  },
});
