import { StyleSheet, Dimensions } from 'react-native';
import { ThemeColors } from '../context/ThemeContext';

const { width: SCREEN_WIDTH } = Dimensions.get('window');

export const getWorkoutStyles = (colors: ThemeColors) => StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background, paddingTop: 24 },
  content: { paddingHorizontal: 16, paddingTop: 48, paddingBottom: 120 },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 8,
    marginBottom: 16,
  },
  header: { fontSize: 32, fontWeight: '700', color: colors.textPrimary },
  templateButton: {
    fontSize: 16,
    fontWeight: '500',
    color: '#007AFF', // This color is fine for both themes
  },
  loadingText: {
    textAlign: 'center',
    color: colors.textSecondary,
    marginTop: 48,
  },
  yesterdayIndicator: {
    alignItems: 'center',
    justifyContent: 'center',
    height: 32,
    marginBottom: 8,
  },
  yesterdayText: {
    fontSize: 13,
    color: colors.textTertiary,
    fontStyle: 'italic',
  },
  workoutDayHeader: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: colors.surface,
    borderRadius: 12,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    position: 'relative',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 4,
  },
  workoutDayHeaderText: {
    fontSize: 18,
    fontWeight: '600',
    color: colors.textPrimary,
  },
  daySelectorContainer: {
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: colors.border,
    paddingVertical: 16,
    marginBottom: 16,
    overflow: 'visible',
  },
  daySelectorTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.textPrimary,
    textAlign: 'center',
    marginBottom: 16,
  },
  dayButton: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 20,
    marginHorizontal: 4,
    marginVertical: 4,
    backgroundColor: colors.surface,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 4,
  },
  dayButtonText: {
    fontSize: 14,
    fontWeight: '500',
    color: colors.accent,
  },
  restDayButton: {
    backgroundColor: colors.surface,
    borderStyle: 'dashed',
    borderWidth: 1,
    borderColor: colors.border,
  },
  restDayButtonText: {
    color: colors.textSecondary,
    fontStyle: 'italic',
  },
  restDayBadge: {
    fontSize: 10,
    fontWeight: 'bold',
    color: colors.textSecondary,
    position: 'absolute',
    top: -5,
    right: -5,
    backgroundColor: colors.surface,
    paddingHorizontal: 4,
    borderRadius: 4,
  },
  timerToggle: {
    position: 'absolute',
    left: 8,
    top: 0,
    bottom: 0,
    justifyContent: 'center',
    paddingHorizontal: 8,
  },
  timerToggleText: {
    color: '#007AFF',
    fontSize: 12,
    fontWeight: '500',
  },
  restToggle: {
    position: 'absolute',
    right: 8,
    top: 0,
    bottom: 0,
    justifyContent: 'center',
    paddingHorizontal: 8,
  },
  restToggleText: {
    color: '#007AFF',
    fontSize: 12,
    fontWeight: '500',
  },
  exerciseRowContainer: {
    backgroundColor: '#DC2626',
  },
  exerciseDeleteActionContainer: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'center',
    alignItems: 'flex-end',
  },
  exerciseDeleteButton: {
    justifyContent: 'center',
    alignItems: 'center',
    width: 100,
    height: '100%',
    paddingRight: 20,
  },
  addDayButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 20,
    marginHorizontal: 4,
    marginVertical: 4,
    borderWidth: 1,
    borderColor: colors.border,
    borderStyle: 'dashed',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 4,
  },
  addDayButtonText: {
    marginLeft: 4,
    color: colors.textSecondary,
    fontWeight: '500',
  },
  tableContainer: {
    backgroundColor: colors.surface,
    borderRadius: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 4,
  },
  tableInner: {
    borderRadius: 12,
    overflow: 'hidden',
  },
  row: {
    flexDirection: 'row',
    backgroundColor: colors.cardBackground,
    minHeight: 48,
  },
  tableHeader: {
    backgroundColor: colors.surface,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  headerText: {
    paddingVertical: 14,
    paddingHorizontal: 12,
    fontWeight: '600',
    fontSize: 12,
    color: colors.textSecondary,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    textAlignVertical: 'center',
  },
  exerciseCol: { flex: 12 },
  numberCol: { flex: 1, textAlign: 'center', minWidth: 70 },
  targetActualCol: { flex: 1.2, textAlign: 'center', minWidth: 75 },
  cell: { padding: 12, fontSize: 14, alignSelf: 'center', minHeight: 48, color: colors.textPrimary },
  addButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 16,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    marginTop: 8,
  },
  addButtonText: { fontSize: 16, fontWeight: '500', color: colors.textPrimary },
  emptyStateContainer: {
    padding: 32,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 24,
  },
  emptyStateText: {
    fontSize: 16,
    color: colors.textSecondary,
  },
});
